#!/usr/bin/env python

import os.path

import slackup


if __name__ == '__main__':
    from sys import argv, exit

    if len(argv) < 2:
        print (
            'Usage: slackup [comma-separated channel names] [filename] '
            '([filename]...)'
        )
        exit(1)

    channels = argv[1]
    filenames = argv[2:]

    for filename in filenames:
        slackup.upload(channels.split(','), os.path.expanduser(filename))
